### PR TITLE
Fix css validation on contacte page

### LINKED ISSUE #47: Fix css validation on contact page
@cylia93 you need to remove the values in the fields and put placeholders instead, otherwise the validation does not work!

image

### PR DESCRIPTION
**Pull request by cylia93**

### CODE REVIEW

File: views/templates/commons/head.php [hunk 1]
```diff
@@ -19,6 +19,9 @@
     <!-- JS LIBRAIRIES -->
     <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
 			  crossorigin="anonymous"></script>
+<!-- Jquery validate plugin -->
+        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.3/jquery.validate.js"></script>
+
```
Comment (Emimint) [inline views/templates/commons/head.php]: @cylia93 I did not read it all but you can have a look here for how to enforce the rules : https://jqueryvalidation.org/documentation/ . Also you can check the version which we should use.

**Review by Emimint — APPROVED** [review]

**Review by f-zahra — APPROVED** [review]
